### ISSUE TITLE
Build-Error during Typemap Generation

### ISSUE THREAD

**Issue by shifty91** [gentryx/libgeodecomp#43] opened 2016-08-27 17:25 UTC
The current master (a871273fb2b0d57e9ee9176887ae5363273f74c9) of LibGeoDecomp doesn't build for me. The reason seems to be an issue during the MPI typemap generation:

`/home/kurt/git/libgeodecomp/tools/typemapgenerator/mpiparser.rb:138:in resolve_forest': incomplete type hierarchy: could not resolve any in ["LibGeoDecomp::Chronometer", "LibGeoDecomp::CoordBox", "LibGeoDecomp::CoordBoxMPIDatatypeHelper", "LibGeoDecomp::FixedArray", "LibGeoDecomp::Streak", "LibGeoDecomp::StreakMPIDatatypeHelper", "LibGeoDecomp::TestCell", "LibGeoDecomp::TestCellMPIDatatypeHelper"] (RuntimeError)
        from /home/kurt/git/libgeodecomp/tools/typemapgenerator/typemapgenerator.rb:31:in generate_forest'
        from /home/kurt/git/libgeodecomp/src/../tools/typemapgenerator/generate.rb:172:in <main>'
src/CMakeFiles/geodecomp.dir/build.make:61: recipe for target '../src/communication/typemaps.h' failed`

The complete build log can be found at https://hawo.net/~ly80toro/log/lgd_build_log_20160827.txt.
If you need any more information, let me know.

**Comment by gentryx** [comment] 2016-08-28 00:09
This is caused by our code not being able to parse the output of recent DoxyGen versions. I'll try to fix this ASAP. Quick fix: disable typemap generation.

**Comment by gentryx** [comment] 2016-08-28 08:19
I'm traveling right now, but as a quick fix you could disable type map generation via CMake. The issue is caused by a change of the output format in recent versions of DoxyGen. I shall investigate.

Thanks!
-Andi

Am 27. August 2016 19:25:30 MESZ, schrieb Kurt Kanzenbach <notifications@github.com>:
>The current master (a871273fb2b0d57e9ee9176887ae5363273f74c9) of
>LibGeoDecomp doesn't build for me. The reason seems to be an issue
>during the MPI typemap generation:
>
>`/home/kurt/git/libgeodecomp/tools/typemapgenerator/mpiparser.rb:138:in
>resolve_forest': incomplete type hierarchy: could not resolve any in
>["LibGeoDecomp::Chronometer", "LibGeoDecomp::CoordBox",
>"LibGeoDecomp::CoordBoxMPIDatatypeHelper", "LibGeoDecomp::FixedArray",
>"LibGeoDecomp::Streak", "LibGeoDecomp::StreakMPIDatatypeHelper",
>"LibGeoDecomp::TestCell", "LibGeoDecomp::TestCellMPIDatatypeHelper"]
>(RuntimeError)
>from
>/home/kurt/git/libgeodecomp/tools/typemapgenerator/typemapgenerator.rb:31:in
>generate_forest'
>from
>/home/kurt/git/libgeodecomp/src/../tools/typemapgenerator/generate.rb:172:in
><main>'
>src/CMakeFiles/geodecomp.dir/build.make:61: recipe for target
>'../src/communication/typemaps.h' failed`
>
>The complete build log can be found at
>https://hawo.net/~ly80toro/log/lgd_build_log_20160827.txt.
>If you need any more information, let me know.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gentryx/libgeodecomp/issues/43

-- 
Sent from my mobile. No type gold.

**Comment by shifty91** [comment] 2016-08-28 18:33
Disabling typemap generation by using `-DWITH_TYPEMAPS=FALSE` works for now. Thanks.

**Comment by gentryx** [comment] 2017-05-29 04:50
closed in 862c44de2dbaecc9d2ad7618790e1b907b92d3f2

**Closed by gentryx** 2017-05-29 04:50 UTC
Labels: bug
